name: leaf_healer
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  dio: ^5.3.3
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  dot_navigation_bar: ^1.0.2
  animated_notch_bottom_bar: ^1.0.3
  giffy_dialog: ^2.1.0
  camera: ^0.10.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  youtube_player_flutter: ^9.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
